# Generated by Django 4.1.7 on 2023-04-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAcademia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='RG',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='RG',
            field=models.CharField(max_length=10),
        ),
    ]
