# Generated by Django 4.1.7 on 2023-04-01 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAcademia', '0002_funcionario_rg_alter_aluno_rg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='nome',
            new_name='Nome',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='plano',
            new_name='Plano',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='cargo',
            new_name='Cargo',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='nome',
            new_name='Nome',
        ),
    ]
