# Generated by Django 4.1.7 on 2023-04-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAcademia', '0003_rename_nome_aluno_nome_rename_plano_aluno_plano_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='CPF',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='CPF',
        ),
        migrations.AddField(
            model_name='aluno',
            name='Telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='Telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
